const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'simurg-training-lab-ui.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'simurg-training-lab.css'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'sw.js'), 'utf8');
const muscleAnatomy = require('../simurg-muscle-anatomy.js');
const anatomyAssets = require('../simurg-training-lab-anatomy-assets.js');
const anatomyAsset = path.join(root, 'assets', 'simurg-anatomy-base-v1.png');
const maskRoot = path.join(root, 'assets', 'anatomy-masks');

assert.match(index, /<section id="training-lab" class="section"/);
assert.match(index, /SimurgTrainingLabUI\.open\(this\)/);
assert.match(ui, /SimurgTrainingLabAnalysis\.analyze\(source,selected\)/);
assert.match(index, /data-key="training-lab" onclick="SimurgPerformanceUI\.open\(\)"/);
assert.match(ui, /simurgV8Go\('training-lab','training-lab'\)/);
assert.match(ui, /function anatomy\(selected,exercise\)/);
assert.match(ui, /anatomyRenderer\.legacyPlan\('asset_preflight_pending'\)/);
assert.match(ui, /anatomyRenderer\.loadPlan/);
assert.match(ui, /loadRendererPlan/);
assert.match(ui, /data-renderer-version=/);
assert.match(ui, /data-hit-area-mode=/);
assert.match(ui, /Training Lab · Intelligence v1/);
assert.match(ui, /VISUAL_ROLE_OVERRIDES/);
assert.deepEqual(anatomyAssets.visualRoleOverrides.prone_y_raise, {primary:['lower_traps'],secondary:['rotator_cuff','posterior_deltoid']});
assert.deepEqual(anatomyAssets.visualRoleOverrides.romanian_deadlift, {primary:['hams'],secondary:['glutes','spinal_erectors']});
assert.deepEqual(anatomyAssets.visualRoleOverrides.sumo_deadlift, {primary:['glutes'],secondary:['hams','quads','adductors','spinal_erectors']});
assert.match(ui, /manualSelection=!exercise&&selected&&state\.muscle===selected\.id&&VISUAL_REGION_MAP\[selected\.id\]/);
assert.match(ui, /preserveAspectRatio="xMidYMid meet"/);
assert.equal(anatomyAssets.baseImageUrl, './assets/simurg-anatomy-base-v1.png');
assert.ok(fs.existsSync(anatomyAsset), 'original local anatomy artwork must exist');
assert.ok(fs.statSync(anatomyAsset).size < 1024 * 1024, 'anatomy artwork must stay below 1 MB');
assert.match(sw, /assets\/simurg-anatomy-base-v1\.png/);
assert.doesNotMatch(ui, /tlBodyShade|class="tlBody"|class="tlContours"/);
const visualRegions = ['pectoralis_sternal','pectoralis_clavicular','abs','obliques','anterior_deltoid','middle_deltoid','biceps','forearms','quads','hip_flexors','adductors','upper_traps','lower_traps','spinal_erectors','lats','rotator_cuff','posterior_deltoid','triceps_long','triceps_lateral','glutes','hams','calves'];
assert.equal(visualRegions.length, 22);
for (const id of visualRegions) assert.ok(anatomyAssets.regionMap[id], `${id} must have a registry region`);
for (const id of visualRegions) {
  const mask = path.join(maskRoot, `${id}.png`);
  assert.ok(fs.existsSync(mask), `${id} must have an anatomy-aligned PNG mask`);
  assert.ok(fs.statSync(mask).size < 64 * 1024, `${id} mask must remain lightweight`);
  assert.match(sw, new RegExp(`assets/anatomy-masks/${id}\\.png`));
}
assert.match(ui, /function mask\(item,highlights\)/);
assert.match(ui, /class="tlAnatomyMasks"/);
assert.match(ui, /class="tlAnatomyHitMap"/);
assert.match(ui, /data-tl-region/);
assert.match(ui, /data-tl-group/);
assert.match(ui, /data-selected-muscle=/);
assert.match(ui, /data-selected-exercise=/);
assert.match(ui, /data-tl-exercise/);
assert.match(ui, /function visualId\(id\)/);
assert.match(ui, /function visualAnatomy\(result\)/);
assert.match(ui, /row\.date>result\.period\.cutoff/);
assert.match(ui, /Array\.isArray\(exercise\.muscles\)/);
assert.match(ui, /mapping\.primaryMuscles/);
assert.match(ui, /mapping\.secondaryMuscles/);
assert.match(ui, /state\.muscle=id/);
assert.match(ui, /VISUAL_REGION_MAP\[id\]/);
assert.match(ui, /Haftalık Anatomik Dağılım/);
for (const label of ['Egzersiz Geçmişi ve İlerleme', 'İlerleme', 'Plateau kontrolü', 'Kas Katkısı · Hafta Karşılaştırması']) assert.match(ui, new RegExp(label));
assert.match(ui, /presentationPriority/);
assert.match(css, /\.tlRecordGrid\{display:grid;grid-template-columns:repeat\(4/);
assert.match(css, /\.tlIntelligencePanel\.has-caution/);
for (const label of ['Pectoralis Major Clavicular', 'Pectoralis Major Sternal', 'Latissimus Dorsi', 'Anterior Deltoid', 'Posterior Deltoid', 'Vastus Lateralis', 'Rectus Femoris']) assert.ok(muscleAnatomy.muscles.some(item => item.label === label), label);
assert.match(ui, /<details class="tlCalculation"><summary>Hesaplama Notu/);
assert.doesNotMatch(ui, /<details class="tlCalculation" open/);
assert.match(ui, /eşlenmemiş hareket · workload dışında tutuldu/);
for (const metric of ['Set katkısı', 'Tekrar', 'Antrenman günü', 'Anlamlı hacim']) assert.match(ui, new RegExp(metric));
assert.doesNotMatch(ui, /DATA\.workouts\s*=|localStorage\.setItem|setInterval|MutationObserver/);
assert.match(css, /@media\(max-width:900px\)/);
assert.match(css, /\.tlSummary\{display:grid;grid-template-columns:repeat\(4/);
assert.match(css, /\.tlMuscleGrid\{display:grid;grid-template-columns:repeat\(3/);
assert.match(css, /@media\(max-width:900px\)[\s\S]*?\.tlMuscleGrid\{grid-template-columns:repeat\(2/);
assert.match(css, /@media\(max-width:900px\)[\s\S]*?\.tlMuscle b\{font-size:9px;white-space:normal;overflow:visible;text-overflow:clip/);
assert.match(css, /\.tlMask\.primary/);
assert.match(css, /\.tlMask\.secondary/);
assert.match(css, /\.tlAnatomyStage\{position:relative/);
assert.match(css, /\.tlAnatomyStage\{[^}]*aspect-ratio:2\/3;overflow:hidden;contain:layout paint/);
assert.match(css, /\.tlAnatomyBase\{[^}]*object-fit:contain/);
assert.match(css, /\.tlMask\{[^}]*mask-image:var\(--tl-mask\)[^}]*mix-blend-mode:color/);
assert.match(css, /--tl-active:#e12d3f/);
assert.match(css, /\.tlMask\.primary\{--tl-mask-color:#e12d3f/);
assert.match(css, /\.tlMask\.secondary\{--tl-mask-color:#eb7041/);
assert.doesNotMatch(css, /\.tlRegion\.primary/);
assert.doesNotMatch(css, /\.tlRegion\.secondary/);
assert.doesNotMatch(css, /\.tlRegion\.active/);
assert.doesNotMatch(ui, /tlGlow|feGaussianBlur/);

function regionSubpaths(id) {
  const item = anatomyAssets.getRegion(id);
  assert.ok(item?.hitPath, `${id} registry hit path must exist`);
  return item.hitPath.split(/\s+Z\s*/).filter(Boolean).map(pathData => {
    const values = [...pathData.matchAll(/-?\d+(?:\.\d+)?/g)].map(item => Number(item[0]));
    const xs = values.filter((_, index) => index % 2 === 0);
    const ys = values.filter((_, index) => index % 2 === 1);
    return { minX: Math.min(...xs), maxX: Math.max(...xs), minY: Math.min(...ys), maxY: Math.max(...ys) };
  });
}

const [leftLat, rightLat] = regionSubpaths('lats');
assert.ok(leftLat.minX >= 620 && leftLat.maxX <= 755, 'left lat must stay within the visible latissimus tissue');
assert.ok(rightLat.minX >= 770 && rightLat.maxX <= 900, 'right lat must stay within the visible latissimus tissue');
assert.ok(leftLat.maxX < rightLat.minX, 'lat regions must not cover the central spinal/erector channel');
assert.ok(leftLat.maxY <= 675 && rightLat.maxY <= 675, 'lat highlight must stop above the lumbar/hip region');

const [leftAnteriorDelt, rightAnteriorDelt] = regionSubpaths('anterior_deltoid');
assert.ok(leftAnteriorDelt.minX >= 125 && leftAnteriorDelt.maxX <= 190, 'left anterior deltoid must stay on the front shoulder cap');
assert.ok(rightAnteriorDelt.minX >= 350 && rightAnteriorDelt.maxX <= 415, 'right anterior deltoid must stay on the front shoulder cap');
assert.ok(leftAnteriorDelt.maxY <= 405 && rightAnteriorDelt.maxY <= 405, 'anterior deltoid hit regions must stay on the visible shoulder cap');

assert.equal(regionSubpaths('abs').length, 10, 'abs highlight must follow the individual abdominal segments');
assert.equal(regionSubpaths('quads').length, 6, 'quads highlight must follow the three visible heads on both legs');
assert.equal(regionSubpaths('calves').length, 4, 'calves highlight must follow the visible gastrocnemius and soleus tissue');
const detailedLowerTraps = regionSubpaths('lower_traps');
assert.equal(detailedLowerTraps.length, 2, 'lower traps must preserve the central spine channel');
assert.ok(detailedLowerTraps[0].maxX <= 758 && detailedLowerTraps[1].minX >= 764, 'lower traps must not paint across the spine');
const detailedErectors = regionSubpaths('spinal_erectors');
assert.equal(detailedErectors.length, 2, 'spinal erectors must be rendered as two narrow lumbar columns');
assert.ok(detailedErectors[0].maxX - detailedErectors[0].minX <= 50 && detailedErectors[1].maxX - detailedErectors[1].minX <= 50, 'spinal erectors must not cover the full lower back');
assert.doesNotMatch(index.match(/<section id="gym"[\s\S]*?<section id="daily"/)?.[0] || '', /Training Lab|tlMuscle|tlDistribution/);
process.stdout.write('✓ Training Lab is a separate read-only responsive app section\n');
